### ISSUE TITLE
prepare_flexreceptor4.py no output

### ISSUE THREAD

**Issue by mpperez3** [Valdes-Tresanco-MS/AutoDockTools_py3#3]
I found a possible issue at:

AutoDockTools\Utilities24\prepare_flexreceptor4.py

I try the following command on AutoDockTools_py3
python.exe AutoDockTools\Utilities24\prepare_flexreceptor4.py   -r "Fib_MGTOOL.pdbqt" -g "Fib_RIGID.pdbqt" -x "Fib_FLEX.pdbqt" -s Fib_MGTOOL:P:THR22,Fib_MGTOOL:Q:GLY51

without any error, but also without any of the expected files as output. I try the same arguments and file on the official AutoDockTools and it generates the expected output. 

Here is the pbdqt file of the example https://anonymousfiles.io/x0WrqlTn/

How I can fix this issue?
Many thanks in advance.

**Comment by Valdes-Tresanco-MS** [comment]
Sorry for the delay, for some reason Github didn't notify me.

Let's see, I have tried several structures and it works as expected. 

When you go to send files you can do it directly here, FilesTranfer, Google Drive, Dropbox, or any other secure means. I do not check any files that are not secure. With the risk involved, I checked the one you shared, and apparently, it has 912 TORSDOF which doesn't make sense. This is just a glance though, please consider sending the file to me securely. If you can send me the files correctly I can review them. In case Github doesn't accept the format, just change the file extension to txt

Best!
Mario S.

**Comment by Valdes-Tresanco-MS** [comment]
@mpperez3 Did you solve the problem?

**Comment by mpperez3** [comment]
Dear @Valdes-Tresanco-MS sorry for delay.
Sorry for the insecure shared link. Here is the reuploaded file in one of the proposed websites https://filetransfer.io/data-package/fn6w2g8c#link. 
I agree with your idea that the problem lies in the file. It is the first that I think. Nevertheless, when I check the same file on the AutoDockTools_py3 with the same command options, it works without errors, and the program generates a file output. AutoDockTools_py4 executes without error but also without output. 

For the moment, I have opted to use the py3 version as long as I don't find the problem.

thank you very much for your support

**Comment by Valdes-Tresanco-MS** [comment]
I have been doing some tests and comparing them with the results of the original and so far it works as expected. In this case, the *FLEX.pdbqt file will only contain the rotatable groups for the THR since the GLY does not contain any rotatable bond and it is ignored. I have used exactly your command line and it works as expected.
What do you mean by AutoDockTools_py4?
Unfortunately, I cannot reproduce this problem. If possible, please record a video and send it to me, that way I can better understand the differences we get.
I am attaching the output files that I get.
[Fib_MGTOOL_result.zip](https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3/files/6330131/Fib_MGTOOL_result.zip)

Best!
Mario S.
